server:
  port: 8080
  servlet:
    session:
      persistent: true

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true

custom:
  property:
    - 1
    - 2
    - 3
    - 4
    - 5
  string-list:
    - hello
    - world
    - spring
    - boot
